Repository EngineHub/WorldEdit, pull requests merged in 2020-04, with the labels that each got.

#1277 Use custom radix sort for ordering blocks
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  gradle.properties
  worldedit-core/build.gradle.kts
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/reorder/ChunkBatchingExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/RegionOptimizedVectorSorter.java
  worldedit-core/src/test/java/com/sk89q/worldedit/internal/util/RegionOptimizedVectorSorterTest.java
  worldedit-forge/build.gradle.kts
Labels: status:accepted, type:performance

#1293 Limit direction names
  worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
Labels: status:accepted, type:bug

#1290 Don't suggest default namespaces.
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/SuggestionHelper.java
Labels: status:accepted

#1285 Delay command block active update if needed
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitBlockCommandSender.java
Labels: platform:bukkit-spigot-paper, status:accepted, type:bug

#1308 Allow craftscripts to exit early + cleanly
  buildSrc/src/main/kotlin/PlatformConfig.kt
  worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/invoke/ReturnException.java
  worldedit-core/src/main/java/com/sk89q/worldedit/scripting/CraftScriptContext.java
Labels: status:accepted, type:feature-request

#561 Add compatibility handlers for beds and banners for MCEdit Schematics
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/MCEditSchematicReader.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/legacycompat/BannerBlockCompatibilityHandler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/legacycompat/BedBlockCompatibilityHandler.java
Labels: status:accepted
