Repository EngineHub/WorldEdit, pull requests merged in 2020-08, with the labels that each got.

#1465 Fail if any mask fails to parse
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/MaskFactory.java
Labels: status:accepted, type:bug

#1301 Add tracing feature to EditSessions
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/TracedEditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/WorldEditCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/EnumConverter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/event/extent/EditSessionEvent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/AbstractPlayerActor.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/TracingExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/scripting/CraftScriptContext.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: status:accepted

#1486 Create schematics folder on startup
  worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/SchematicsEventListener.java
Labels: status:accepted, type:feature-request

#1482 Update for Spigot 1.16.2.
  worldedit-bukkit/src/main/resources/worldedit-adapters.jar
Labels: platform:bukkit-spigot-paper, status:accepted

#1476 Copy the class source validator from WG.
  worldedit-bukkit/src/main/java/com/sk89q/bukkit/util/ClassSourceValidator.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
Labels: platform:bukkit-spigot-paper, status:accepted

#1489 Add -c to deform and make -o act like it does in //gen.
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
Labels: status:accepted, type:bug

#1491 Added a brush for biomes
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BiomeCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/factory/BiomeFactory.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: status:accepted

#1506 Deprecate BlockQuirkExtent, handle lower down
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/world/BlockQuirkExtent.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricWorld.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeWorld.java
Labels: status:accepted, type:tech-debt
