Repository EngineHub/WorldEdit, pull requests merged in 2020-10, with the labels that each got.

#1555 Move to packaged translations
  buildSrc/src/main/kotlin/TranslationFileCheck.kt
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitServerInterface.java
  worldedit-cli/src/main/java/com/sk89q/worldedit/cli/CLIPlatform.java
  worldedit-core/build.gradle.kts
  worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/AbstractPlatform.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/Platform.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/io/file/ArchiveUnpacker.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/translation/TranslationManager.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricPlatform.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgePlatform.java
  worldedit-sponge/src/main/java/com/sk89q/worldedit/sponge/SpongePlatform.java
Labels: status:accepted, type:feature-request

#1545 Add ^x,y,z relative offset support to the offset parser
  worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/OffsetConverter.java
Labels: status:accepted, type:feature-request

#1563 Use /tool in /toggleeditwand description
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: status:accepted, type:tech-debt

#1564 Fix loading dev i18n files
  buildSrc/src/main/kotlin/PlatformConfig.kt
  worldedit-core/build.gradle.kts
  worldedit-core/src/main/java/com/sk89q/worldedit/util/translation/TranslationManager.java
Labels: status:accepted, type:bug

#1566 Ensure that the wand can be used before giving it
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/NavigationWand.java
Labels: status:accepted, type:feature-request

#1576 Move archive unpack into WE working dir
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/AbstractPlatform.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/io/file/ArchiveUnpacker.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/translation/TranslationManager.java
Labels: status:accepted, type:bug
