Repository EngineHub/WorldEdit, pull requests merged in 2020-11, with the labels that each got.

#1595 Add instructions for unbinding tools/brushes on equip.
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolCommands.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: status:accepted, type:feature-request

#1597 Saner Translation Loading
  buildSrc/src/main/kotlin/PlatformConfig.kt
  worldedit-core/src/main/java/com/sk89q/worldedit/util/translation/TranslationManager.java
Labels: status:accepted, type:bug

#1598 Implement UPDATE for Fabric
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricPlatform.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/internal/ExtendedChunk.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/internal/FabricWorldNativeAccess.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/mixin/MixinWorldChunk.java
  worldedit-fabric/src/main/resources/worldedit.mixins.json
Labels: platform:fabric, status:accepted, type:bug
