Repository EngineHub/WorldEdit, pull requests merged in 2021-11, with the labels that each got.

#1930 Update paperweight + userdev bundle.
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/AdapterConfig.kt
  worldedit-bukkit/adapters/adapter-1.17.1/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1.17.1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/v1_17_R1_2/PaperweightAdapter.java
  worldedit-bukkit/build.gradle.kts
Labels: type:tech-debt

#1926 Add getBrush helper for use with instanceof pattern matching
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  worldedit-core/src/main/java/com/sk89q/jnbt/CompoundTag.java
  worldedit-core/src/main/java/com/sk89q/jnbt/ListTag.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/BlockTool.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/DoubleActionBlockTool.java
  worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/asset/AssetLoaders.java
Labels: type:feature-request, status:accepted

#1942 If a trace hits the world limit, cancel it
  worldedit-core/src/main/java/com/sk89q/worldedit/util/TargetBlock.java
Labels: type:bug, status:accepted
