Repository EngineHub/WorldEdit, pull requests merged in 2021-01, with the labels that each got.

#1638 Support Lucko's Fabric Permissions API
  worldedit-fabric/build.gradle.kts
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricPermissionsProvider.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricWorldEdit.java
  worldedit-fabric/src/main/resources/fabric.mod.json
Labels: status:accepted, type:feature-request

#1641 Run chunk deleter in Fabric
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricWorldEdit.java
Labels: platform:fabric, status:accepted, type:bug

#1632 Correct ellipsoid region selector initialization
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/selector/EllipsoidRegionSelector.java
Labels: type:bug

#1633 Alter the CUI lifecycle to be more consistent and reliable
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayer.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/CUIChannelListener.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditListener.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/event/platform/SessionIdleEvent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/session/SessionManager.java
  worldedit-fabric/build.gradle.kts
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricPlayer.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricWorldEdit.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/net/handler/WECUIPacketHandler.java
  worldedit-fabric/src/main/resources/fabric.mod.json
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgePlayer.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeWorldEdit.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/net/handler/WECUIPacketHandler.java
  worldedit-sponge/src/main/java/com/sk89q/worldedit/sponge/CUIChannelHandler.java
  worldedit-sponge/src/main/java/com/sk89q/worldedit/sponge/SpongePlayer.java
  worldedit-sponge/src/main/java/com/sk89q/worldedit/sponge/SpongeWorldEdit.java
Labels: type:bug

#1651 Update so many dependencies, merge Forge/Fabric for final jar
  COMPILING.md
  README.md
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/CommonConfig.kt
  buildSrc/src/main/kotlin/PlatformConfig.kt
  buildSrc/src/main/kotlin/Versions.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
  worldedit-bukkit/build.gradle.kts
  worldedit-cli/build.gradle.kts
  worldedit-core/build.gradle.kts
  worldedit-core/doctools/build.gradle.kts
  worldedit-core/doctools/src/main/kotlin/com/sk89q/worldedit/internal/util/DocumentationPrinter.kt
  worldedit-fabric/build.gradle.kts
  worldedit-forge/build.gradle.kts
  worldedit-mod/README.md
  worldedit-mod/build.gradle.kts
  worldedit-sponge/build.gradle.kts
Labels: status:accepted, type:tech-debt

#1654 Allow UPDATE mixin to soft-fail on Fabric
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricPlatform.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/internal/MixinConfigPlugin.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/mixin/MixinWorldChunkSetBlockHook.java
  worldedit-fabric/src/main/resources/worldedit.mixins.json
Labels: platform:fabric, status:accepted, type:bug
