Repository EngineHub/WorldEdit, pull requests merged in 2021-07, with the labels that each got.

#1808 Optimize legacy schematic loading
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/MCEditSchematicReader.java
Labels: status:accepted, type:performance

#1811 Fix CLI Mess
  worldedit-cli/build.gradle.kts
  worldedit-cli/src/main/java/com/sk89q/worldedit/cli/CLIExtraCommands.java
  worldedit-cli/src/main/java/com/sk89q/worldedit/cli/CLIWorldEdit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
Labels: platform:cli, type:tech-debt

#1821 [Fabric] Update to 1.17.1
  worldedit-fabric/build.gradle.kts
Labels: platform:fabric, status:accepted, type:bug

#1833 Fix setting biomes on negative-Y-enabled worlds.
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/mixin/MixinBiomeArray.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeWorld.java
Labels: status:accepted, type:bug

#1832 1.17 for master
  CHANGELOG.txt
  buildSrc/src/main/kotlin/CommonConfig.kt
  buildSrc/src/main/kotlin/PlatformConfig.kt
  worldedit-bukkit/build.gradle.kts
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
  worldedit-bukkit/src/main/resources/worldedit-adapters.jar
  worldedit-cli/build.gradle.kts
  worldedit-cli/src/main/java/com/sk89q/worldedit/cli/CLIExtraCommands.java
  worldedit-cli/src/main/java/com/sk89q/worldedit/cli/CLIWorldEdit.java
  worldedit-core/src/main/java/com/sk89q/util/StringUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/MCEditSchematicReader.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/Constants.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/wna/WorldNativeAccess.java
  worldedit-fabric/build.gradle.kts
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/internal/FabricWorldNativeAccess.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/mixin/MixinBiomeArray.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeWorld.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/internal/ForgeWorldNativeAccess.java
Labels: status:accepted, type:tech-debt

#1843 Only map options if needed to replace seed
  worldedit-bukkit/src/main/resources/worldedit-adapters.jar
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricWorld.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeWorld.java
Labels: status:accepted, type:bug

#1847 [Forge] Update to 1.17.1
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/PlatformConfig.kt
  gradle/wrapper/gradle-wrapper.properties
  worldedit-bukkit/build.gradle.kts
  worldedit-core/build.gradle.kts
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricAdapter.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricPlayer.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricWorld.java
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/internal/FabricWorldNativeAccess.java
  worldedit-forge/build.gradle.kts
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/CommandWrapper.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeAdapter.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeBiomeRegistry.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeBlockCategoryRegistry.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeBlockMaterial.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeBlockRegistry.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeDataFixer.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeEntity.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeEntityProperties.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeItemCategoryRegistry.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeItemRegistry.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgePermissionsProvider.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgePlatform.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgePlayer.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeWatchdog.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeWorld.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeWorldEdit.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ThreadSafeCache.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/WorldEditFakePlayer.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/WorldEditGenListener.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/internal/ForgeTransmogrifier.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/internal/ForgeWorldNativeAccess.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/internal/IPropertyAdapter.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/internal/NBTConverter.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/internal/TileEntityUtils.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/net/handler/InternalPacketHandler.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/net/handler/PacketHandlerUtil.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/net/handler/WECUIPacketHandler.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/net/packet/LeftClickAirEventMessage.java
  worldedit-forge/src/main/resources/META-INF/accesstransformer.cfg
Labels: platform:forge, status:accepted, type:feature-request
