Repository EngineHub/WorldEdit, pull requests merged in 2022-03, with the labels that each got.

#556 Fluid masks for forge/fabric.
  worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricWorld.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeWorld.java
Labels: type:feature-request, status:accepted

#2065 Use Forge's official tag API
  worldedit-forge/build.gradle.kts
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeBlockCategoryRegistry.java
  worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgeItemCategoryRegistry.java
Labels: platform:forge, status:accepted, type:tech-debt

#2066 Fix terminology in SECURITY.md
  SECURITY.md
Labels: status:accepted, type:tech-debt
